#************************** MDIS4 device descriptor *************************
#
# lm63_max.dsc: Descriptor for LM63
# Automatically generated by mdiswiz 1.5.012_beta-linux-5 from 13y00106.xml
# 2005-11-24
#
#****************************************************************************

lm63_1 {

    # ------------------------------------------------------------------------
    #        general parameters (don't modify)
    # ------------------------------------------------------------------------
    DESC_TYPE = U_INT32 0x1
    HW_TYPE = STRING LM63

    # ------------------------------------------------------------------------
    #        reference to base board
    # ------------------------------------------------------------------------
    BOARD_NAME = STRING smbpci_ich
    DEVICE_SLOT = U_INT32 0x0

    # ------------------------------------------------------------------------
    #        device parameters
    # ------------------------------------------------------------------------

    # remote temp offset (signed-int32 -55..125) [°C]
    # Range: 0..125
    RMT_TEMP_OFFSET = U_INT32 0

    # SMBus bus number
    SMB_BUSNBR = U_INT32 0

    # SMBus address of LM63
    SMB_DEVADDR = U_INT32 0x98

    # pulse per revolution fan tachometer
    # Range: 1..3
    TACH_PULSE = U_INT32 3

    # ------------------------------------------------------------------------
    #        debug levels (optional)
    #        these keys have only effect on debug drivers
    # ------------------------------------------------------------------------
    DEBUG_LEVEL = U_INT32 0xc0008000
    DEBUG_LEVEL_MK = U_INT32 0xc0008000
    DEBUG_LEVEL_OSS = U_INT32 0xc0008000
    DEBUG_LEVEL_DESC = U_INT32 0xc0008000
}
# EOF
